{% set name = "xmpppy" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xmpppy-{{ version }}.tar.gz
  sha256: c0f4ab504cfecf8b127d857b260e480598ae5522cb7b084c84537503646b3bb6

build:
  entry_points:
    - xmpp-message = xmpp.cli:simple_message
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - six

test:
  imports:
    - xmpp
  commands:
    - pip check
    - xmpp-message --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/xmpppy/xmpppy
  summary: XMPP implementation in Python
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akrherz
